name: Manually deploy to Cocoapods

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  deploy-cocoapods-manual:
    name: Manually deploy to Cocoapods
    runs-on: macOS-latest
    if: startsWith(github.ref, 'refs/heads/main')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
